### ISSUE TITLE
Insert Node in bestehenden Baum

### ISSUE THREAD

**Issue by danihegglin** [faberchri/tree-builder-2#14]
Funktion muss die Cobweb/Classit Funktionen benutzen um neue Nodes Top-Down einzufügen

**Comment by danihegglin** [comment]
Weiss nicht mehr was Juk gesagt hat. Glabue die Funktionen waren New, Incorporate. Splite & Merge sollte weggelassen werden. Ist das korrekt?

**Comment by faberchri** [comment]
ja hab ich auch so in Erinnerung.
