### ISSUE TITLE
Visualisierung erweitern

### ISSUE THREAD

**Issue by danihegglin** [faberchri/tree-builder-2#2]
Visualisierung sollte auch Daten der einzelnen Nodes anzeigen

**Comment by danihegglin** [comment]
Funktionalität ist da, effektive Daten fehlen aber noch

**Comment by faberchri** [comment]
cool wäre eine Visualisierung à la: http://www.roguewave.com/portals/0/products/imsl-numerical-libraries/java-library/docs/6.1/manual/default.htm?turl=WordDocuments%2Fdendrogramchart.htm

**Comment by danihegglin** [comment]
Aktualisierung des Baums muss geschmeidiger sein

**Comment by danihegglin** [comment]
Problem mit Memory bei der Anzeige der Attribute
